config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
  omniauth_providers: [:facebook, :google_oauth2, :github],
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :admin, only: [:index, :create, :update]

  resources :notes do
    resources :note_items, only: [:new, :create, :edit, :update, :destroy]
  end


  resources :quiz_games, only: [:index, :show, :create, :edit, :update, :destroy]


  resources :rooms, only: [:new, :create, :show, :destroy] do
    resources :messages, only: [:create]
    resources :questions, only: [:create]
  end

end

app/models/note.rb
class Note < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :note_items, dependent: :destroy
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [ :show, :edit, :update, :destroy ]

  # GET /notes or /notes.json
  def index
    if params[:invite].present?
      encrypted_url = params[:invite]
      _, note_id = ApplicationRecord.decrypt_url(encrypted_url) # user_id, note_id
      note = Note.find_by(id: note_id)

      if note.nil?
        redirect_to root_path
        return
      end

      if !current_user.notes.include?(note)
        current_user.notes << note
      end
      redirect_to note_url(note)
    else
      @notes = current_user.notes
    end
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = current_user.notes.build
  end

  # GET /notes/1/edit
  def edit
  end

  # note /notes or /notes.json
  def create
    @note = current_user.notes.build(note_params)

    respond_to do |format|
      if current_user.save
        format.html { redirect_to note_url(@note), notice: "note was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "note was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    current_user.notes.destroy(@note)

    if @note.users.count == 0
      @note.destroy
    end

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "note was successfully destroyed." }
    end
  end

  private

    def set_note
      @note = current_user.notes.find_by(id: params[:id])
      if @note.nil?
        redirect_to root_path
      end
    end

    def note_params
      params.require(:note).permit(:title)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<div>
  <p>
    <strong>Title:</strong>
    <%= note.title %>
  </p>

  <h3>Items:</h3>

  <%= turbo_frame_tag dom_id(note) do %>
    <% note.note_items.each do |note_item| %>
      <%= render note_item, {note: note} %>
    <% end %>
  <% end %>

  <%= link_to "New note_item", new_note_note_item_path(note), data: {turbo_frame: dom_id(note, 'new_note_item')} %>
  <%= turbo_frame_tag dom_id(note, 'new_note_item') %>
</div>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Show this note", @note %> |
  <%= link_to "Back to notes", notes_path %>
</div>

app/views/notes/index.html.erb
<% @notes.each do |note| %>
  <% if note.users.count > 1 %>
    <%= turbo_stream_from dom_id(note) %>
  <% end %>
<% end %>

<h1>Notes</h1>

<%= link_to "Home", root_path %>
<%= link_to "New note", new_note_path %>

<div id="notes">
  <% @notes.each do |note| %>
    <%= render note %>
    <%= link_to "Show this note", note %>
    <hr/>
  <% end %>
</div>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Back to notes", notes_path %>
</div>

app/views/notes/show.html.erb
<%= turbo_stream_from dom_id(@note) %>

<div>
  users: <%= @note.users.map { |user| user.email }.join(", ") %>
</div>

<%= render @note %>

<div>
  <%= link_to "Edit this note", edit_note_path(@note) %> |
  <%= link_to "Back to notes", notes_path %>

  <%= button_to "Destroy this note", @note, method: :delete %>
</div>

<div>invite url: <%= "https://#{request.host_with_port}#{notes_path}?invite=#{ApplicationRecord.create_encrypted_url(current_user.id, @note.id)}" %></div>