config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
  omniauth_providers: [:facebook, :google_oauth2, :github],
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :admin, only: [:index, :create, :update]

  resources :notes do
    resources :note_items, only: [:new, :create, :edit, :update, :destroy]
  end


  resources :quiz_games, only: [:index, :show, :create, :edit, :update, :destroy]


  resources :rooms, only: [:new, :create, :show, :destroy] do
    resources :messages, only: [:create]
    resources :questions, only: [:create]
  end

end

app/models/quiz_game.rb
class QuizGame < ApplicationRecord
  has_many :quiz_game_users
  has_many :users, through: :quiz_game_users
  has_many :quiz_players, dependent: :destroy
end

app/controllers/quiz_games_controller.rb
require 'net/http'
require 'fileutils'

class QuizGamesController < ApplicationController

  INIT_PARAMS = {
      'name' => 'New Game',
      'questions_source' => 'Gpt4AiQuestions::MythicalLocationsQuestion'
    }

  REDIS_EXPIRING_TIMER = 120

  before_action :set_quiz_game, only: [ :show, :edit, :update, :destroy ]

  def index
    if params[:invite].present?
      encrypted_url = params[:invite]
      _, quiz_game_id = ApplicationRecord.decrypt_url(encrypted_url) # user_id, quiz_game_id
      quiz_game = QuizGame.find_by(id: quiz_game_id)

      if quiz_game.nil?
        redirect_to root_path
        return
      end

      if !current_user.quiz_games.include?(quiz_game)
        current_user.quiz_games << quiz_game
      end

      if quiz_game.game_status == "configuring"
        redirect_to edit_quiz_game_path(quiz_game)
      else
        redirect_to quiz_game_path(quiz_game)
      end

    else
      @quiz_games = current_user.quiz_games
    end
  end

  def show
    if params[:player_action] == 'option_сlicked'
      player = @quiz_game.quiz_players.find_by(player_id: current_user.id)

      Turbo::StreamsChannel.broadcast_append_to(
        "quiz_game_show_#{@quiz_game.id}",
        target: "main_form_option_#{params[:main_form][:player_answer]}",
        partial: "quiz_games/game/player_choice",
        locals: { player_color: player.player_color }
      )
      head :ok
      return
    end

    if params[:player_action] == 'form_submit'
      Turbo::StreamsChannel.broadcast_action_to(
        "quiz_game_show_#{@quiz_game.id}",
        action: 'form_submit'
      )
      head :ok
      return

    end

    questions_model = Object.const_get(@quiz_game.questions_source)
    @questions_quantity = questions_model.count
    questions_counter = @quiz_game.questions_counter
    @current_question = questions_model.find_by(id: questions_counter)
    main_form_params = params[:main_form]

    if main_form_params.present?

      if main_form_params[:request_type] == "next"

        if questions_counter >= @questions_quantity
          render :show, locals: {response_type: "end"}
          return
        end

        client_questions_counter = main_form_params[:questions_counter]
        if questions_counter != client_questions_counter
          @quiz_game.update!(questions_counter: client_questions_counter)
        end

        @current_question = questions_model.find_by(id: @quiz_game.questions_counter)
        render :show, locals: {response_type: "next"}

      elsif main_form_params[:request_type] == "restart"

        @quiz_game.update!(questions_counter: 1)
        @current_question = questions_model.find_by(id: @quiz_game.questions_counter)
        @quiz_game.quiz_players.each do |quiz_player|
          quiz_player.player_answers = []
          quiz_player.save!
        end

        render :show, locals: {response_type: "answer"}

      else

        guiz_player = QuizPlayer.find_by(player_id: current_user.id)
        player_answer = ((main_form_params[:player_answer] == @current_question.correct_answer) ? 1 : 0)
        guiz_player.player_answers << player_answer
        guiz_player.save!

        head :ok

      end

    else
      guiz_player = QuizPlayer.find_by(player_id: current_user.id)
      if !@quiz_game.quiz_players.include?(guiz_player)
        @quiz_game.quiz_players.create(player_id: current_user.id, player_color: set_player_color(current_user.id))
      end

      render :show, locals: {response_type: "next"}
    end

  end

  def create
    @quiz_game = current_user.quiz_games.build

    respond_to do |format|
      if current_user.save
        format.html { redirect_to edit_quiz_game_path(@quiz_game), notice: "quiz_game was successfully created." }
      else
        format.html { render :index, status: :unprocessable_entity }
      end
    end
  end

  def edit
    if @quiz_game.game_status == "started"
      redirect_to quiz_game_path(@quiz_game)
      return
    end

    redis = Redis.new

    if params[:quiz_game].present?
      redis.setex("quiz_game_edit_#{@quiz_game.id}", REDIS_EXPIRING_TIMER, params[:quiz_game].to_json)
      @config_params = params[:quiz_game]
    else
      if redis_data = redis.get("quiz_game_edit_#{@quiz_game.id}")
        @config_params = JSON.parse(redis_data)
      else
        redis.setex("quiz_game_edit_#{@quiz_game.id}", REDIS_EXPIRING_TIMER, INIT_PARAMS.to_json)
        @config_params = INIT_PARAMS
      end
    end

    if params[:quiz_game].present?
      client_id = params[:client_id]

      Turbo::StreamsChannel.broadcast_update_later_to(
        "quiz_game_edit_#{@quiz_game.id}",
        target: "quiz_game_#{@quiz_game.id}",
        partial: "quiz_games/form",
        locals: {
          url: quiz_game_path(@quiz_game),
          config_params: @config_params,
          client_id: client_id,
          model_names: get_models_names
        }.as_json
      )

      head :ok
    else
      render :edit, locals: {config_params: @config_params, model_names: get_models_names}
    end
  end

  def update

    if @quiz_game.game_status == "started"
      redirect_to quiz_game_path(@quiz_game), notice: "Game was already started."
      return
    end

    redis = Redis.new
    redis.del("quiz_game_#{@quiz_game.id}")

    if @quiz_game.update(quiz_game_params.merge(game_status: 'started'))

      Turbo::StreamsChannel.broadcast_update_later_to(
        "quiz_game_edit_#{@quiz_game.id}",
        target: "quiz_game_#{@quiz_game.id}",
        html: "<meta url='#{quiz_game_path(@quiz_game)}'/>"
      )
      head :ok
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    # ================================
    redis = Redis.new
    redis.del("requests_counter_#{@quiz_game.id}")
    # ================================

    current_user.quiz_games.destroy(@quiz_game)

    if @quiz_game.users.count == 0
      @quiz_game.destroy
    end

    respond_to do |format|
      format.html { redirect_to quiz_games_url, notice: "quiz_game was successfully destroyed." }
    end
  end

  private

    def set_quiz_game
      @quiz_game = current_user.quiz_games.find_by(id: params[:id])
      if @quiz_game.nil?
        redirect_to root_path
      end
    end

    def quiz_game_params
      params.require(:quiz_game).permit(:name, :questions_source)
    end

    def set_player_color(player_id)
      hue = (((player_id - 1) * 137.508) % 360)
      "hsl(#{hue}, 100%, 50%)"
    end

    def get_models_names
      models_names = []

      Dir.glob('app/models/*/*').each do |file_path|
        next if !file_path.include?('.rb')

        relative_path = file_path.sub('app/models/', '').sub('.rb', '')
        class_name  = relative_path.split('/').map(&:camelize).join('::')

        models_names << class_name
      end

      models_names.reverse!
    end

end

app/helpers/quiz_games_helper.rb
module QuizGamesHelper
end

app/views/quiz_games/_form.html.erb
<%= form_with scope: :quiz_game,
							url: local_assigns["url"],
							method: :patch,
							html: { class: "quiz_game_edit_form" },
							data: { client_id: local_assigns["client_id"] }	do |form| %>

  <div class="quiz_game_edit_form_submit">
    <%= form.submit "Start game" %>
  </div>

  <div class="quiz_game_edit_form_header">
    <%= form.label "Game name:", style: "display: block" %>
    <%= form.text_field :name, {autofocus: true, value: local_assigns["config_params"]["name"]} %>
  </div>

  <div class="quiz_game_edit_form_body">
    <% local_assigns["model_names"].each do |source_name| %>
      <div class="quiz_game_edit_form_item">
        <%= form.radio_button :questions_source, source_name, checked: local_assigns["model_names"][0] == source_name %>
        <%= form.label "questions_source_#{source_name.split('::').join.downcase}", name = source_name.split('::').last.gsub('Questions', '').gsub(/([a-z])([A-Z])/, '\1 \2') %>
        <%= print_alert_span(source_name) %>
      </div>
    <% end %>
  </div>

<% end %>

app/views/quiz_games/edit.html.erb
<%= turbo_stream_from "quiz_game_edit_#{@quiz_game.id}" %>


<div class="quiz_games_edit">

  <h1>Config game</h1>

  <div class="quiz_games_edit_controls">
    <%= link_to "Back to all quiz games", quiz_games_path %>
    <%= button_to "Delete", @quiz_game, method: :delete, class: "quiz_games_edit_controls_delete" %>
  </div>

  <div class="quiz_games_edit_invite" data-controller="clipboard">
    <h4>Invite url:</h4>
    <span class="quiz_games_edit_invite_link" data-clipboard-target="source">
      <%= "https://#{request.host_with_port}#{quiz_games_path}?invite=#{ApplicationRecord.create_encrypted_url(current_user.id, @quiz_game.id)}" %>
    </span>
    <button class="quiz_games_edit_invite_copy" data-action="clipboard#copy">Copy link</button>
  </div>

  <div data-controller="quiz_game_edit" class="quiz_games_edit_body">
    <%= turbo_frame_tag dom_id(@quiz_game) do %>
      <%= render "form", { 
			url: quiz_game_path(@quiz_game), 
			config_params: config_params, 
			client_id: 'no_client',
			model_names: model_names
			}.as_json %>
    <% end %>
  </div>

</div>

app/views/quiz_games/index.html.erb
<div class="quiz_games_index">
  <h1>Quiz games</h1>

  <div class="quiz_games_index_controls">
    <%= link_to "Home", root_path %>
    <%= button_to "Create a new quiz game", quiz_games_path %>
  </div>

  <div id="quiz_games" class="quiz_games_index_games">
    <% @quiz_games.each do |quiz_game| %>
      <div class="quiz_games_index_game">
        <h3><%= quiz_game.name %></h3>
        <%= link_to "Show this quiz game", edit_quiz_game_path(quiz_game) %>
      </div>
    <% end %>
  </div>
</div>

app/views/quiz_games/show.html.erb
<%= turbo_stream_from "quiz_game_show_#{@quiz_game.id}" %>

<div class="quiz_games_show">

  <h1>Quiz</h1>

  <div class="quiz_games_show_header">
    <div class="quiz_games_show_controls">
      <%= link_to "Back to quiz games", quiz_games_path %>
      <%= button_to "Delete", @quiz_game, method: :delete, class: "quiz_games_show_controls_delete" %>
    </div>
    <div>
      <h4>Users:</h4>
      <% @quiz_game.quiz_players.each do |player| %>
        <div class="quiz_games_show_users">
          <% user = @quiz_game.users.find_by(id: player.player_id) %>
          <span><%= user ? (user.name || user.email) : 'anonymous' %></span>
          <span class="quiz_games_show_user_color" style="background-color: <%= player.player_color %>"></span>
        </div>
      <% end %>
    </div>
  </div>

  <div class="quiz_games_show_invite" data-controller="clipboard">
    <h4>Invite url:</h4>
    <span class="quiz_games_show_invite_link" data-clipboard-target="source">
      <%= "https://#{request.host_with_port}#{quiz_games_path}?invite=#{ApplicationRecord.create_encrypted_url(current_user.id, @quiz_game.id)}" %>
    </span>
    <button class="quiz_games_show_invite_copy" data-action="clipboard#copy">Copy link</button>
  </div>



  <div data-controller="quiz_game_show" class="quiz_games_show_body">
    <% if response_type == "end" %>
      <%= render "quiz_games/game/game_score", quiz_game: @quiz_game, questions_quantity: @questions_quantity %>
    <% else %>
      <%= render "quiz_games/game/main_form",
							quiz_game: @quiz_game,
							current_question: @current_question,
							response_type: response_type %>
    <% end %>
  </div>

  <div class="quiz_games_show_counter">
    <%= @quiz_game.questions_counter %>/<%= @questions_quantity %>
  </div>

</div>