config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
  omniauth_providers: [:facebook, :google_oauth2, :github],
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :admin, only: [:index, :create, :update]

  resources :notes do
    resources :note_items, only: [:new, :create, :edit, :update, :destroy]
  end


  resources :quiz_games, only: [:index, :show, :create, :edit, :update, :destroy]


  resources :rooms, only: [:new, :create, :show, :destroy] do
    resources :messages, only: [:create]
    resources :questions, only: [:create]
  end

end

app/models/note_item.rb
class NoteItem < ApplicationRecord
  belongs_to :note

  validates :body, presence: true

  after_create_commit -> {
    broadcast_append_later_to self,
    partial: 'note_items/note_item',
    locals: {note: self.note, note_item: self},
    target: "note_#{self.note.id}"
  }

  after_update_commit -> {
    broadcast_replace_later_to self,
    partial: 'note_items/note_item',
    locals: {note: self.note, note_item: self},
    target: "note_item_#{self.id}"
  }

  after_destroy_commit -> {
    broadcast_remove_to self,
    target: "note_item_#{self.id}"
  }
end

app/controllers/note_items_controller.rb
class NoteItemsController < ApplicationController
  before_action :set_note
  before_action :set_note_item, only: [ :edit, :update, :destroy ]

  def new
    @note_item = @note.note_items.build
  end

  def edit
  end

  def create
    @note_item = @note.note_items.build(note_item_params)

    respond_to do |format|
      if @note_item.save
        format.html { redirect_to note_path(@note), notice: "note_item was successfully created." }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @note_item.update(note_item_params)
        format.html { redirect_to note_path(@note), notice: "note was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @note_item.destroy!

    respond_to do |format|
      format.html { redirect_to note_path(@note), notice: "note_item was successfully destroyed." }
      format.turbo_stream
    end
  end

  private

    def set_note_item
      @note_item = @note.note_items.find(params[:id])
    end

    def set_note
      @note = Note.find(params[:note_id])
    end

    def note_item_params
      params.require(:note_item).permit(:body)
    end
end

app/helpers/note_items_helper.rb
module NoteItemsHelper
end

app/views/note_items/_form.html.erb
<%= form_with(model: [note, note_item]) do |form| %>
  <% if note_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(note_item.errors.count, "error") %> prohibited this note_item from being saved:</h2>

      <ul>
        <% note_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/note_items/_note_item.html.erb
<%= turbo_frame_tag dom_id(note_item) do %>
  <div id="<%= dom_id note_item %>" class="note_item">
    <p><%= note_item.body %></p>
    <%= link_to "Edit", edit_note_note_item_path(note, note_item) %>
    <%= button_to "Destroy", note_note_item_path(note, note_item), method: :delete %>
  </div>
<% end %>

app/views/note_items/create.turbo_stream.erb
<%= turbo_stream.append 'note_items' do %>
  <%= render partial: "note_items/note_item", locals: { note: @note, note_item: @note_item } %>
<% end %>
<%= turbo_stream.update dom_id(@note, 'new_note_item'), '' %>

app/views/note_items/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@note_item) %>

app/views/note_items/edit.html.erb
<h1>Editing note_item</h1>

<%= turbo_frame_tag dom_id(@note_item) do %>
  <div class="edit_note_item">
    <%= render "form", note: @note, note_item: @note_item %>
    <%= link_to "x", note_path(@note) %>
  </div>
<% end %>

app/views/note_items/new.html.erb
<h1>New note_item</h1>

<%= turbo_frame_tag dom_id(@note, 'new_note_item') do %>
  <div class="new_note_item">
    <%= render "form", note: @note, note_item: @note_item %>
    <%= link_to "x", note_path(@note) %>
  </div>
<% end %>